env=PROD
#api config
PROD.api_url=https://api.github.com
DEV.api_url=https://dev.api.github.com
PROD.restful_api_url=https://api.restful-api.dev
api_token= your api token


# web config

saucedemo_url=https://saucedemo.com

#
browser =chrome
selenium_url = http://localhost:4444/wd/hub

#java "-Dwebdriver.chrome.driver=D:\java-solvd\selenium\chromedriver.exe" -jar "D:\java-solvd\selenium\selenium-server-4.44.0.jar" standalone --session-timeout 9999
